1. 【强制】禁止使用 generator 生成器，异步处理可使用 async、await、Promise。airbnb 编码规范指出，生成器目前不能很好地转换成 es5 语法；
2. 【强制】async 函数不能既不使用 await，又未返回 promise。eslint：[@typescript-eslint/require-await](https://typescript-eslint.io/rules/require-await)；
3. 【强制】await 需要使用在 thenable 对象（包含 then 方法的对象，比如 Promise 实例）前。eslint：[@typescript-eslint/await-thenable](https://typescript-eslint.io/rules/await-thenable)；

- <Badge type="error">BAD</Badge>

```jsx | pure
async function fetchData() {
  const result = await 123; // 123 不是 thenable 对象
  console.log(result);
}
```

- <Badge type="success">GOOD</Badge>

```jsx | pure
async function fetchData() {
  const result = await Promise.resolve(123); // 使用符合 thenable 协议的对象
  console.log(result);
}
```

4. 【强制】使用 await 语句不能造成竞争性的赋值冲突，比如两个 await 都会赋值同一变量，但它们的执行顺序不定。eslint：[require-atomic-updates](https://eslint.org/docs/latest/rules/require-atomic-updates)；

- <Badge type="error">BAD</Badge>

```jsx | pure
async function updateData() {
  let value = 0;
  await Promise.resolve();
  value++;
  await Promise.resolve();
  value++;
  console.log(value);
}
```

在上述代码中，两个 await 语句之间的赋值操作 value++ 不是原子的，存在竞争条件。具体执行顺序取决于异步操作的完成时间，可能导致 value 的结果不确定。

修复这个问题的方法是确保在 await 语句中的赋值操作是原子的，可以通过使用中间变量或者采用其他同步机制来保证操作的原子性。

以下是示例修复的代码：

- <Badge type="success">GOOD</Badge>

```jsx | pure
async function updateData() {
  let value = 0;
  await Promise.resolve();
  let temp = value;
  temp++;
  await Promise.resolve();
  value = temp;
  console.log(value);
}
```

5. 【推荐】使用 Error 错误对象作为 reject 的参数，这样便于追踪问题。eslint：[prefer-promise-reject-errors](https://eslint.org/docs/latest/rules/prefer-promise-reject-errors)；

- <Badge type="error">BAD</Badge>

```jsx | pure
function fetchData() {
  return new Promise((resolve, reject) => {
    reject('Something went wrong');
  });
}
```

在上述代码中，reject 方法的参数是一个字符串而不是 Error 对象。这样做可能会导致在错误追踪和处理方面存在一些限制，因为字符串不包含有关错误的详细信息，如堆栈跟踪等。

修复这个问题的方法是使用 Error 对象作为 reject 方法的参数：

- <Badge type="success">GOOD</Badge>

```jsx | pure
function fetchData() {
  return new Promise((resolve, reject) => {
    reject(new Error('Something went wrong'));
  });
}
```

6. 【推荐】返回的 Promise 需要有错误捕获处理。eslint：[@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises)；

- <Badge type="error">BAD</Badge>

```jsx | pure
async function fetchData() {
  // 返回的 Promise 没有被捕获处理
  fetch('https://api.example.com/data');
}
```

- <Badge type="success">GOOD</Badge>

```jsx | pure
async function fetchData() {
  try {
    await fetch('https://api.example.com/data');
    // 其他处理逻辑
  } catch (error) {
    // 错误处理逻辑
  }
}
```

7. 【推荐】返回的 Promise 需要被正确使用，即通过 then 回调或 await 取出 fulfilled 值。eslint：[@typescript-eslint/no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises)；

- <Badge type="error">BAD</Badge>

```jsx | pure
async function fetchData() {
  return new Promise((resolve, reject) => {
    // Promise 被创建但未被使用
    fetch('https://api.example.com/data');
  });
}
```

在上述代码中，fetch 函数返回的 Promise 被创建但未被使用，没有通过 then 回调或 await 取出其结果。这可能导致 Promise 的结果无法正确处理，从而产生错误或悬挂的 Promise。

修复这个问题的方法是通过 then 回调或 await 取出 Promise 的结果，并对结果进行适当的处理：

- <Badge type="success">GOOD</Badge>

```jsx | pure
async function fetchData() {
  return new Promise((resolve, reject) => {
    fetch('https://api.example.com/data')
      .then((response) => {
        // 处理成功的情况
        resolve(response);
      })
      .catch((error) => {
        // 处理错误的情况
        reject(error);
      });
  });
}
```

8. 【强制】【umijs/lint】new Promise(executor) 参数 executor 不能使用 async 函数，没必要且 async 错误不被捕获。eslint：[no-async-promise-executor](https://eslint.org/docs/latest/rules/no-async-promise-executor)；

- <Badge type="error">BAD</Badge>

```jsx | pure
const myPromise = new Promise(async (resolve, reject) => {
  // 异步函数在 Promise 的执行器中被使用
  const result = await someAsyncFunction();
  resolve(result);
});
```

在上述代码中，async 函数被用作 Promise 的执行器，这是不推荐的做法。由于执行器在创建 Promise 实例时会立即执行，而异步函数的执行是异步的，因此异步函数的行为无法被正确捕获和处理。

为了修复这个问题，可以将异步函数转换为使用传统的同步操作或者返回一个新的 Promise，以确保执行器函数的同步性：

- <Badge type="success">GOOD</Badge>

```jsx | pure
const myPromise = new Promise((resolve, reject) => {
  someAsyncFunction()
    .then((result) => {
      resolve(result);
    })
    .catch((error) => {
      reject(error);
    });
});
```

9. 【强制】【umijs/lint】executor 不能有返回值。eslint：[no-promise-executor-return](https://eslint.org/docs/latest/rules/no-promise-executor-return)；

- <Badge type="error">BAD</Badge>

```jsx | pure
const myPromise = new Promise((resolve, reject) => {
  // 执行器函数返回了一个值
  return someValue;
});
```

在上述代码中，执行器函数返回了一个值 someValue，这是不推荐的做法。执行器函数不应该有返回值，因为 Promise 的结果是通过 resolve 或 reject 方法来确定的，而不是通过执行器函数的返回值。

为了修复这个问题，可以简单地移除执行器函数的返回语句：

- <Badge type="success">GOOD</Badge>

```jsx | pure
const myPromise = new Promise((resolve, reject) => {
  // 执行器函数没有返回值
  // 执行其他操作...
});
```

10. 【参考】不能在循环体内使用 await，这样会使迭代等待执行完成，此种场景可使用 Promise.all，然后再进行遍历。eslint：[no-await-in-loop](https://eslint.org/docs/latest/rules/no-await-in-loop)；

- <Badge type="error">BAD</Badge>

```jsx | pure
async function processItems(items) {
  for (const item of items) {
    await doSomething(item);
  }
}
```

在上述代码中，循环体内部使用了 await 关键字，导致每次迭代都会等待 doSomething 方法的执行完成。这种写法可能会降低并发性能，特别是当循环次数较大时。

为了修复这个问题，可以使用 Promise.all 方法将所有的异步操作包装成一个 Promise 数组，然后在循环外部使用 await 等待它们的完成：

- <Badge type="success">GOOD</Badge>

```jsx | pure
async function processItems(items) {
  await Promise.all(items.map((item) => doSomething(item)));
}
```
